name: skwer
description: A game collection.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CourierPrime
      fonts:
        - asset: fonts/CourierPrime-Regular.ttf
  shaders:
    - shaders/mosaic_tile_3.frag
    - shaders/mosaic_tile_5.frag
